/**
 * Public surface for pages. Import only from "@/ui".
 * Never import Radix, Recharts, TanStack, motion, lucide, sonner, or date-fns from page code.
 */
export {
  Badge,
  Button,
  Card,
  Dialog,
  Input,
  Select,
  Table,
  Tabs,
  ToastHost,
  Tooltip,
  toast,
  type BadgeProps,
  type ButtonProps,
  type CardProps,
  type DialogProps,
  type InputProps,
  type SelectOption,
  type SelectProps,
  type TableColumn,
  type TableProps,
  type TabsItem,
  type TabsProps,
  type ToastOptions,
  type ToastTone,
  type TooltipProps,
} from './core';

export {
  AccentBeam,
  AiFeatureDeck,
  AiFeaturePanel,
  AiFeatureStage,
  BookingPanel,
  BrandFooter,
  CredentialStrip,
  CTABand,
  FeatureBento,
  LogoMarquee,
  MarketingHero,
  ProcessSection,
  ProductShowcase,
  PublicNav,
  PublicShell,
  ResultRail,
  SpotlightCard,
  TestimonialRail,
  type AccentBeamProps,
  type AiFeatureDeckProps,
  type AiFeatureItem,
  type AiFeaturePanelProps,
  type AiFeatureStageProps,
  type BookingPanelProps,
  type BookingSlot,
  type BookingTreatment,
  type BrandFooterLink,
  type BrandFooterProps,
  type CredentialStripItem,
  type CredentialStripProps,
  type CTABandProps,
  type CTALink,
  type FeatureBentoItem,
  type FeatureBentoProps,
  type FeatureBentoVariant,
  type LogoMarqueeItem,
  type LogoMarqueeProps,
  type MarketingCta,
  type MarketingHeroProps,
  type MarketingHeroVariant,
  type ProcessSectionProps,
  type ProcessStep,
  type ProductShowcaseItem,
  type ProductShowcaseProps,
  type PublicNavCta,
  type PublicNavItem,
  type PublicNavProps,
  type PublicShellProps,
  type ResultRailItem,
  type ResultRailProps,
  type SpotlightCardProps,
  type TestimonialRailItem,
  type TestimonialRailProps,
} from './public';

export {
  ActivityFeed,
  ChartCard,
  DataTable,
  EmptyState,
  FilterBar,
  OpsShell,
  PageHeader,
  RiskQueue,
  StatCard,
  type ActivityFeedItem,
  type ActivityFeedProps,
  type ChartCardProps,
  type ChartCardRow,
  type ChartCardType,
  type ChartCardDensity,
  type ChartCardValueFormat,
  type DataTableColumn,
  type DataTableProps,
  type EmptyStateProps,
  type FilterBarFilter,
  type FilterBarProps,
  type OpsShellNavItem,
  type OpsShellProps,
  type OpsShellAppearance,
  type PageHeaderProps,
  type PageHeaderAction,
  type RiskQueueItem,
  type RiskQueueProps,
  type RiskSeverity,
  type StatCardProps,
  type StatCardVariant,
} from './ops';

export {
  MotionHeroItem,
  MotionHover,
  MotionPage,
  MotionReveal,
  MotionStagger,
  MotionStaggerItem,
} from './motion';

export { formatDate, formatRelative, formatTime } from './lib/format';

export { UiIcon } from '../components/UiIcons';

export {
  SkeletonComposer,
  composeSkeletonLayout,
  getSkeleton,
  type ComposedSkeletonLayout,
  type SkeletonComposerProps,
  type SkeletonId,
  type SkeletonSlots,
} from './compose/SkeletonComposer';
export {
  CATALOGUE_COMPONENTS,
  SKELETONS,
  getCatalogueComponentNames,
  type ComponentMeta,
  type SkeletonDefinition,
  type UiSurface,
} from './registry';
