/**
 * Public surface for pages. Import only from "@/ui".
 * Never import Radix, Recharts, or TanStack from page code.
 */
export {
  Badge,
  Button,
  Card,
  Dialog,
  Input,
  Select,
  Table,
  Tabs,
  Tooltip,
  type BadgeProps,
  type ButtonProps,
  type CardProps,
  type DialogProps,
  type InputProps,
  type SelectOption,
  type SelectProps,
  type TableColumn,
  type TableProps,
  type TabsItem,
  type TabsProps,
  type TooltipProps,
} from './core';

export {
  BrandFooter,
  CTABand,
  FeatureBento,
  MarketingHero,
  ProcessSection,
  ProductShowcase,
  PublicShell,
  TestimonialRail,
  type BrandFooterLink,
  type BrandFooterProps,
  type CTABandProps,
  type CTALink,
  type FeatureBentoItem,
  type FeatureBentoProps,
  type FeatureBentoVariant,
  type MarketingCta,
  type MarketingHeroProps,
  type MarketingHeroVariant,
  type ProcessSectionProps,
  type ProcessStep,
  type ProductShowcaseItem,
  type ProductShowcaseProps,
  type PublicShellProps,
  type TestimonialRailItem,
  type TestimonialRailProps,
} from './public';

export {
  ActivityFeed,
  ChartCard,
  DataTable,
  EmptyState,
  FilterBar,
  OpsShell,
  PageHeader,
  StatCard,
  type ActivityFeedItem,
  type ActivityFeedProps,
  type ChartCardProps,
  type ChartCardRow,
  type ChartCardType,
  type DataTableColumn,
  type DataTableProps,
  type EmptyStateProps,
  type FilterBarFilter,
  type FilterBarProps,
  type OpsShellNavItem,
  type OpsShellProps,
  type PageHeaderProps,
  type StatCardProps,
} from './ops';

export { SkeletonComposer, getSkeleton, type SkeletonComposerProps, type SkeletonId, type SkeletonSlots } from './compose/SkeletonComposer';
export {
  CATALOGUE_COMPONENTS,
  SKELETONS,
  getCatalogueComponentNames,
  type ComponentMeta,
  type SkeletonDefinition,
  type UiSurface,
} from './registry';
