"""Restore must honor ledgered AI repairs even when attempt rows under-report."""
from __future__ import annotations

from app.application.candidate_generation.call_budget import (
    CANDIDATE_CALL_BUDGET_POLICY_REVISION,
    CandidateCallBudget,
)
from app.core.config import settings


def test_restore_uses_approved_events_when_attempts_undercount_repair() -> None:
    snapshot = {
        "policy_revision": CANDIDATE_CALL_BUDGET_POLICY_REVISION,
        "total_used": 3,
        "substage_used": {
            "foundation": 0,
            "data_exports": 0,
            "business_components": 2,
            "pages": 1,
            "routes": 0,
            "validation": 0,
        },
        "events": [
            {
                "kind": "approved",
                "stage": "business_components",
                "wall_elapsed_ms": 1,
                "attempt_type": "ai",
                "used_before": 0,
                "failure_code": "",
                "provider": "openrouter",
                "model": settings.V2_CANDIDATE_COMPONENT_MODEL,
                "idempotency_key": "rev:business_components:gen:0",
            },
            {
                "kind": "approved",
                "stage": "business_components",
                "wall_elapsed_ms": 2,
                "attempt_type": "ai_repair",
                "used_before": 1,
                "failure_code": "",
                "provider": "openrouter",
                "model": settings.V2_CANDIDATE_COMPONENT_MODEL,
                "idempotency_key": "rev:business_components:repair:0",
            },
            {
                "kind": "approved",
                "stage": "pages",
                "wall_elapsed_ms": 3,
                "attempt_type": "ai",
                "used_before": 2,
                "failure_code": "",
                "provider": "openrouter",
                "model": settings.V2_CANDIDATE_PAGE_MODEL,
                "idempotency_key": "rev:pages:gen:0",
            },
        ],
        "checkpoints": {},
    }
    attempts = [
        {
            "attempt_id": "gen-comp",
            "request_id": 1,
            "candidate_revision_uuid": "rev",
            "substage": "business_components",
            "provider": "openrouter",
            "model": settings.V2_CANDIDATE_COMPONENT_MODEL,
            "http_status": 200,
            "response_top_level_keys": ["files"],
            "response_format": "structured_json",
            "provider_request_id": "",
            "raw_payload_sha256": "a" * 64,
            "duration_ms": 10,
            "input_tokens": 1,
            "output_tokens": 1,
            "total_tokens": 2,
            "typed_result": "completed",
            "error_code": "",
            "retryable": False,
            "retry_attempted": False,
            "terminal_decision": "completed",
            "parent_attempt_id": "",
            "idempotency_key": "rev:business_components:gen:0",
            "error_type": "",
            "error_message_redacted": "",
            "error_metadata_keys": [],
            "request_shape_hash": "",
            "capability_profile_revision": "",
            "retry_decision_reason": "",
            "fallback_model_decision": "",
            "calls_remaining": 3,
            "context_window": None,
            "estimated_input_tokens": None,
            "requested_output_tokens": None,
            "clamped_output_tokens": None,
            "minimum_output_allowance": None,
            "context_reserve": None,
            "approval_decision": "approved",
        },
        {
            "attempt_id": "gen-pages",
            "request_id": 1,
            "candidate_revision_uuid": "rev",
            "substage": "pages",
            "provider": "openrouter",
            "model": settings.V2_CANDIDATE_PAGE_MODEL,
            "http_status": 200,
            "response_top_level_keys": ["files"],
            "response_format": "structured_json",
            "provider_request_id": "",
            "raw_payload_sha256": "b" * 64,
            "duration_ms": 10,
            "input_tokens": 1,
            "output_tokens": 1,
            "total_tokens": 2,
            "typed_result": "completed",
            "error_code": "",
            "retryable": False,
            "retry_attempted": False,
            "terminal_decision": "completed",
            "parent_attempt_id": "",
            "idempotency_key": "rev:pages:gen:0",
            "error_type": "",
            "error_message_redacted": "",
            "error_metadata_keys": [],
            "request_shape_hash": "",
            "capability_profile_revision": "",
            "retry_decision_reason": "",
            "fallback_model_decision": "",
            "calls_remaining": 1,
            "context_window": None,
            "estimated_input_tokens": None,
            "requested_output_tokens": None,
            "clamped_output_tokens": None,
            "minimum_output_allowance": None,
            "context_reserve": None,
            "approval_decision": "approved",
        },
    ]

    budget = CandidateCallBudget.restore(snapshot=snapshot, attempts=attempts)
    restored = budget.snapshot()
    assert restored["total_used"] == 3
    assert restored["substage_used"]["business_components"] == 2
    assert restored["substage_used"]["pages"] == 1
    assert restored["remaining"] == restored["total_max"] - 3
